### ISSUE TITLE
Move tool bar to bottom

### ISSUE THREAD

**Issue by grantwest** [rignaneseleo/SlimSocial-for-Twitter#17]
As phones have gotten bigger, it is now best practice to have tool bars at the bottom of the screen for easy reach. Specifically the home/search/notification/pm buttons should be at the bottom rather than the top. The official twitter app still has the profile button and the little star home settings button at the top, but those are far less often used so I guess it is acceptable.

**Comment by STPKITT** [comment]
I just tried the current version from F-Droid on my device running LineageOS 14.1/Android 7.1.2 and the toolbar is at the bottom!
