### ISSUE TITLE
Sharing a text does not recognize new lines (\n or \r )

### ISSUE THREAD

**Issue by joergi** [rignaneseleo/SlimSocial-for-Twitter#18]
When I share a text from the app EventFahrplan to SlimSocial for Twitter, I have the problem, that `\n` and `\r` not recognized in the SlimSocial for Twitter app.
in all other apps it's working, just not in Slim Social.

In SlimSocial for Twitter it looks like this:
![grafik](https://user-images.githubusercontent.com/1439809/103244203-89a45800-495c-11eb-8eb0-8ef0d45b27d7.png)
![grafik](https://user-images.githubusercontent.com/1439809/103244258-b7899c80-495c-11eb-8cb9-cd1e709faf84.png)

This is how it looks in any other app:
![grafik](https://user-images.githubusercontent.com/1439809/103244212-9163fc80-495c-11eb-967c-de305591b38f.png)

It's related to issue 354 from EventFahrplan
https://github.com/EventFahrplan/EventFahrplan/issues/354

**Comment by STPKITT** [comment]
That issue with the "null " being inserted at the beginning of text also comes up when sharing a message from the XMPP client app Conversations for example.

**Comment by joergi** [comment]
ok, I had a look at the code itself.
for me it looks like, that this is really only a wrapper around the Twitter Mobile page.
so there is not really a chance to fix this issue, right?

**Comment by joergi** [comment]
duplicate to #19 
(when I added #18 - it was failing - and I couldn't see it, that's why I did it a 2nd time...sorry for that)

**Comment by STPKITT** [comment]
So you're not sure if it's fixable, but you close the issue entry anyway? I'd leave it open until someone with knowledge about how the wrapping works has posted actual facts. My guess is that a wrapper can indeed influence behaviour. So please re-open this!

**Comment by joergi** [comment]
It's reopened, the other is a duplicate and closed

**Comment by STPKITT** [comment]
Ok, good, I think I got confused by GitHub's layout.
