### ISSUE TITLE
Changelog update

### ISSUE THREAD

**Issue by bh-e** [rignaneseleo/SlimSocial-for-Twitter#4]
Normally changelog is written bottom to top. New version and its changes comes in top. It would be very nice if you this style.

**Comment by rignaneseleo** [comment]
Thank you for the feedback. 
The changelog in txt file is a reminder for me, I've initially made it to remind what I've changed and to eventually fix bugs. 
The "official" changelog is the one you find in "releases" :)

**Comment by bh-e** [comment]
👍
