### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [rignaneseleo/SlimSocial-for-Twitter#5]
Hi @rignaneseleo 
I found [this app](https://play.google.com/store/apps/details?id=com.mohammed.bashiri.supersocialtwittr) on the Google Play Store. This guys just took your source code, added some ads in it and put it on the Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide a link to this repo in the request, some screenshots of your original app...

**Comment by rignaneseleo** [comment]
Thank you for the report. I've fill and send the report form.

**Comment by Poussinou** [comment]
@rignaneseleo There is also [this one](https://play.google.com/store/apps/details?id=com.narwal.parvesh.litifytwitter) that is exactly the same as yours...
