### ISSUE TITLE
"Copy link to Tweet" is missing

### ISSUE THREAD

**Issue by STPKITT** [rignaneseleo/SlimSocial-for-Twitter#9]
No matter if using twitter.com or mobile.twitter.com in the browser, both offer the option "Copy link to Tweet" when the user clicks on the arrow down symbol to open the context menu.
The official Android app also offers the option to share tweets via any app the user has installed so that tweets can easily be shared via E-Mail, XMPP etc..

Summary: SlimSocial-for-Twitter should offer at least the option to copy Tweet links and ideally also the option to share Tweets.

**Comment by christy500** [comment]
Hi
My copy link to tweet icon is missing, pls what should i do, kindly help. Thanks 

Twitter username -  @chinwechristy7 
Email -  Iheomafavour100@gmail.com
Reply pls. Thanks 

Best Regards 
Iheoma

**Comment by FHS2000** [comment]
> Hi
> My copy link to tweet icon is missing, pls what should i do, kindly help. Thanks
> 
> Twitter username - @chinwechristy7
> Email - [Iheomafavour100@gmail.com](mailto:Iheomafavour100@gmail.com)
> Reply pls. Thanks
> 
> Best Regards
> Iheoma

I am having the same problem. Copy Link to Tweet is missing from both Desktop and Android.  Please help!    Thank you!

**Comment by FHS2000** [comment]
Hi, 
My Copy Link to Tweet option is missing from both Desktop and Android.  Please help! 

Thank you!

**Comment by joergi** [comment]
It's in the app since a longer time 
click on the share button, then you can click "copy link to tweet"
![grafik](https://user-images.githubusercontent.com/1439809/103237997-a4b99c80-4949-11eb-8b58-aadf3ef90427.png)

closes #9

**Comment by STPKITT** [comment]
Thanks @joergi for trying this. I can confirm that it is currently working although Twitter must've changed something in the meantime since the option in question is now found when clicking on the share-symbol instead of the "arrow down"-symbol.
